### ISSUE TITLE
Encrypted data is susceptible to frequency analysis...

### ISSUE THREAD

**Issue by univmalik** [chmuhammadsohaib/NHXCrypt#1]
I hope this is not a professional encryption standard as it is highly susceptible to frequency analysis and chosen plaintext attack... Nontheless I think for guys coming getting into cryptography this might be interesting...

**Comment by chmuhammadsohaib** [comment]
@univmalik It's highly susceptible to frequency analysis if the person knows the exact data. No one would decrypt data if he already knows what's inside the data.
